name: clauderag-demo
version: '3.9'

services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: Admin@123
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  postgres:
    image: pgvector/pgvector:pg16
    container_name: rag-postgres

    environment:
      POSTGRES_DB: ragdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: ${APP_IMAGE}
    container_name: app

    ports:
      - "8081:8080"

    environment:

      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: admin123
      AWS_REGION: us-east-1
      THRESHOLD: ${THRESHOLD}
      EMBEDDING_MODEL: ${EMBEDDING_MODEL}
      TOP_CHUNK: ${TOP_CHUNK}
      CHUNK_SIZE: ${CHUNK_SIZE}
      SWAGGER_UI: ${SWAGGER_UI}
      SWAGGER_API_DOCS: ${SWAGGER_API_DOCS}
      MAX_FILE_SIZE_UPLOAD: ${MAX_FILE_SIZE_UPLOAD}

      CLAUDE_MODEL: ${CLAUDE_MODEL}
      CLAUDE_MODEL_INPUT_TOKEN_LIMIT: ${CLAUDE_MODEL_INPUT_TOKEN_LIMIT}
      API_KEY: ${ANTHROPIC_API_KEY}

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ragdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

    depends_on:
      postgres:
        condition: service_healthy

  ollama:
    image: ollama/ollama:latest
    container_name: ollama

    ports:
      - "11434:11434"

    volumes:
      - ollama_data:/root/.ollama

    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: minio

    ports:
      - "9000:9000"
      - "9001:9001"

    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123

    command: server /data --console-address ":9001"

    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  pgadmin_data:
  ollama_data:
  minio_data: