app:
  file-storage:
    provider: s3
  table-name: document_chunks_v1
  input-token-limit: ${CLAUDE_MODEL_INPUT_TOKEN_LIMIT}
  similarity-threshold: ${THRESHOLD}
  top-chunk: ${TOP_CHUNK}
  chunk-size: ${CHUNK_SIZE}

  llm:
    prompt:
      source:
    active-model: ${OLLAMA_MODEL}

aws:
  access-key: ${AWS_ACCESS_KEY_ID}
  secret-key: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_REGION}
  s3:
    bucket-name: documents
    endpoint: http://minio:9000

springdoc:
  api-docs:
    enabled: ${SWAGGER_API_DOCS}
  swagger-ui:
    enabled: ${SWAGGER_UI}

spring:
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE_UPLOAD}
  application:
    name: rag-demo

  datasource:
    url: jdbc:postgresql://localhost:5432/ragdb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

  ai:
    model:
      chat: ollama
    anthropic:
      api-key: ${API_KEY}

      chat:
        options:
          model: ${CLAUDE_MODEL}
    ollama:
      base-url: http://ollama:11434
      embedding:
        options:
          model: ${EMBEDDING_MODEL}
      chat:
        options:
          model: ${OLLAMA_MODEL}
    #openai:
    #  api-key: ${OPENAI_API_KEY}

    #  chat:
    #    options:
    #      model: gpt-4o-mini

    #  embedding:
    #    options:
    #      model: text-embedding-3-small
ocr:
  tesseract:
    datapath: C:/Users/baby.satheeshkumar/Documents/Seeburger-poc/github-code/organize/rag-platform/testdata
    language: eng
