CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS documents (
    document_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    file_name VARCHAR(500),
    file_hash VARCHAR(64),
    uploaded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Table: public.documents

-- DROP TABLE IF EXISTS public.documents;

CREATE TABLE IF NOT EXISTS documents
(
    document_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_hash character varying(64),
    file_name character varying(500),
    uploaded_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP,
    file_size bigint,
    content_type character varying(50),
    processing_status character varying(20),
    source_file_location character varying(50),
    storage_name character varying(20)
);


CREATE TABLE IF NOT EXISTS document_chunks_claude_llm (
    id BIGSERIAL PRIMARY KEY,
    file_name VARCHAR(255),
    chunk_text TEXT,
    embedding VECTOR(768)
);

CREATE TABLE IF NOT EXISTS document_chunks_v1 (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    document_id BIGINT,
    chunk_index INT,
    chunk_text TEXT,
    chunk_hash VARCHAR(64),
    embedding VECTOR(768),
    CONSTRAINT fk_document_chunks_document
        FOREIGN KEY (document_id)
        REFERENCES documents(document_id)
);


CREATE TABLE IF NOT EXISTS rag_audit (
    id BIGSERIAL PRIMARY KEY,
    user_question TEXT NOT NULL,
    llm_answer TEXT,
    source_chunk TEXT,
    chat_model VARCHAR(255) NOT NULL,
    response_time_ms BIGINT,
    username VARCHAR(255),
    question_asked_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS index_rag_audit_question_asked_at
ON rag_audit(question_asked_at);

CREATE INDEX IF NOT EXISTS index_rag_audit_chat_model
ON rag_audit(chat_model);

CREATE INDEX IF NOT EXISTS index_rag_audit_username
ON rag_audit(username);

CREATE TABLE IF NOT EXISTS prompt_templates
(
    model_name     VARCHAR(100) PRIMARY KEY,
    prompt_content TEXT NOT NULL,
    version        INTEGER,
    updated_at     TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO public.prompt_templates
    (model_name, prompt_content, version)
VALUES
    ('claude-opus-4-5-20251101',
    $$
     You are a document assistant.

     Use STRICTLY the supplied context.

     Context:
     {context}

     Question:
     {question}

     If answer is not found,
     say:
     'Answer not found in document'.
  $$, 2)
ON CONFLICT (model_name) DO NOTHING;